### ISSUE TITLE
Is the style hint meant to render on karzok template website?

### ISSUE THREAD

**Issue by pauleaster** [kogeletey/karzok#2]
Just looking at your website [karzok markdown-syntax](https://fmatch.org/karzok/meta/markdown-syntax/) and noticed that `{% hint style="warning" %} 123 {% endhint %}` did not render. Is it supposed to be like this? Can shortcodes be added directly to markdown or do they need to be enclosed in HTML tags or something else?

**Comment by kogeletey** [comment]
Yes so far they do not work, but I will add in the future. If you want to do it yourself, you can use the shortcodes folder.
See more in [https://www.getzola.org/documentation/content/shortcodes/](https://www.getzola.org/documentation/content/shortcodes/)
