### ISSUE TITLE
.gitignore in static folder causing websites to not render properly

### ISSUE THREAD

**Issue by pauleaster** [kogeletey/karzok#4]
Having */ in `static/.gitignore` is causing the github deploy to fail. Is it necessary to ignore all subfolders? After I built my website I had a number of subfolders that were critical to it working.

**Comment by pauleaster** [comment]
I found that removing `*/` from `static/.gitignore` made it work.

**Comment by kogeletey** [comment]
The fact is that files from node_modules are sent there, they can be generated for localcdn. For local build, I would advise using `npm run gen`  and so the resources are loaded via cdn.
